services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boost_api
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    ports:
      - "8086:3000"
    volumes:
      - ./.env:/app/.env
      - ./backups:/app/backups
    networks:
      - boost_api_default
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: boost_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d
      - ./backups:/backups
    networks:
      - boost_api_default
    restart: unless-stopped
    labels:
      - "data=true"

  redis:
    image: redis:7-alpine
    container_name: boost_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boost_api_default
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  boost_api_default:
    name: boost_api_default

volumes:
  postgres_data:
    name: boost_api_postgres_data
  redis_data:
    name: boost_api_redis_data